In [10]:
# Dependencies and Setup
import pandas as pd

# Files to Load 
Sept2018 = "CSV/JC-201809-citibike-tripdata.csv"
Oct2018 = "CSV/JC-201810-citibike-tripdata.csv"
Nov2018 = "CSV/JC-201811-citibike-tripdata.csv"

# Read from CSV
Sept2018_df = pd.read_csv(Sept2018)
Oct2018_df = pd.read_csv(Oct2018)
Nov2018_df = pd.read_csv(Nov2018)

Oct2018_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,152,2018-10-01 07:44:41.4170,2018-10-01 07:47:14.2960,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,15302,Subscriber,1971,2
1,122,2018-10-01 08:50:05.4340,2018-10-01 08:52:08.2250,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29654,Subscriber,1973,1
2,211,2018-10-01 09:03:17.0640,2018-10-01 09:06:48.0940,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,33621,Subscriber,1958,1
3,342,2018-10-01 10:13:07.0090,2018-10-01 10:18:49.8960,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,26266,Subscriber,1982,1
4,2976,2018-10-01 10:45:14.2800,2018-10-01 11:34:51.2610,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,27083,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39133,1118,2018-10-31 11:30:53.7070,2018-10-31 11:49:32.4850,3694,Jackson Square,40.711130,-74.078900,3185,City Hall,40.717733,-74.043845,26219,Subscriber,1991,1
39134,1242,2018-10-31 12:20:41.6990,2018-10-31 12:41:24.4270,3694,Jackson Square,40.711130,-74.078900,3185,City Hall,40.717733,-74.043845,26288,Customer,1986,1
39135,1188,2018-10-31 12:21:36.2790,2018-10-31 12:41:24.3540,3694,Jackson Square,40.711130,-74.078900,3185,City Hall,40.717733,-74.043845,29591,Customer,1977,1
39136,983,2018-10-31 14:27:59.9590,2018-10-31 14:44:23.2020,3694,Jackson Square,40.711130,-74.078900,3277,Communipaw & Berry Lane,40.714358,-74.066611,32831,Subscriber,1988,1
39137,544,2018-10-31 15:37:41.3760,2018-10-31 15:46:45.5090,3694,Jackson Square,40.711130,-74.078900,3268,Lafayette Park,40.713464,-74.062859,29490,Subscriber,1991,2

In [21]:
Sept_Nov2018_df = Sept2018_df
Sept_Nov2018_df = Sept_Nov2018_df.append(Oct2018_df, ignore_index=True)
Sept_Nov2018_df = Sept_Nov2018_df.append(Nov2018_df, ignore_index=True)

#Sept_Nov2018_df.to_csv("CSV/cleaned/2018.csv")
Sept_Nov2018_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,284,2018-09-01 01:48:22.0320,2018-09-01 01:53:06.9130,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26303,Subscriber,1984,1
1,370,2018-09-01 01:48:22.5010,2018-09-01 01:54:32.9270,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29667,Subscriber,1984,1
2,1181,2018-09-01 09:37:04.3070,2018-09-01 09:56:45.3280,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26307,Customer,1994,1
3,383,2018-09-01 09:44:46.0030,2018-09-01 09:51:09.9230,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,29261,Subscriber,1987,1
4,377,2018-09-01 09:44:46.1850,2018-09-01 09:51:03.6330,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,33665,Subscriber,1985,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103065,734,2018-11-28 10:46:12.6640,2018-11-28 10:58:27.0750,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26255,Subscriber,1994,1
103066,312,2018-11-28 19:52:40.1140,2018-11-28 19:57:52.9270,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,29451,Subscriber,1957,1
103067,914,2018-11-29 10:20:57.7240,2018-11-29 10:36:12.0420,3694,Jackson Square,40.711130,-74.078900,3206,Hilltop,40.731169,-74.057574,29610,Subscriber,1994,1
103068,2392,2018-11-29 17:28:24.1590,2018-11-29 18:08:16.8720,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29659,Subscriber,1994,1
103069,637,2018-11-30 12:00:10.4100,2018-11-30 12:10:48.0210,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29536,Subscriber,1994,1

In [12]:
# Files to Load 
Sept2019 = "CSV/JC-201909-citibike-tripdata.csv"
Oct2019 = "CSV/JC-201910-citibike-tripdata.csv"
Nov2019 = "CSV/JC-201911-citibike-tripdata.csv"

# Read from CSV
Sept2019_df = pd.read_csv(Sept2019)
Oct2019_df = pd.read_csv(Oct2019)
Nov2019_df = pd.read_csv(Nov2019)

Oct2019_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,892,2019-10-01 00:20:05.0140,2019-10-01 00:34:57.3800,3275,Columbus Drive,40.718355,-74.038914,3280,Astor Place,40.719282,-74.071262,29544,Subscriber,1976,1
1,374,2019-10-01 00:43:48.8790,2019-10-01 00:50:03.8190,3211,Newark Ave,40.721525,-74.046305,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,29536,Subscriber,1984,1
2,170,2019-10-01 01:35:51.8630,2019-10-01 01:38:42.5470,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,26304,Subscriber,1986,1
3,946,2019-10-01 02:55:53.4000,2019-10-01 03:11:40.2710,3272,Jersey & 3rd,40.723332,-74.045953,3679,Bergen Ave,40.722104,-74.071455,29496,Customer,1969,0
4,517,2019-10-01 03:10:16.1290,2019-10-01 03:18:53.6350,3206,Hilltop,40.731169,-74.057574,3210,Pershing Field,40.742677,-74.051789,26205,Subscriber,1969,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42248,287,2019-10-31 23:42:25.1120,2019-10-31 23:47:12.6180,3209,Brunswick St,40.724176,-74.050656,3186,Grove St PATH,40.719586,-74.043117,26160,Subscriber,1987,1
42249,532,2019-10-31 23:48:07.5720,2019-10-31 23:56:59.7280,3187,Warren St,40.721124,-74.038051,3187,Warren St,40.721124,-74.038051,26292,Subscriber,1976,0
42250,202,2019-10-31 23:50:04.3480,2019-10-31 23:53:26.6230,3681,Grand St,40.715178,-74.037683,3185,City Hall,40.717733,-74.043845,26180,Subscriber,1977,1
42251,841,2019-10-31 23:53:24.5280,2019-11-01 00:07:25.8950,3199,Newport Pkwy,40.728745,-74.032108,3483,Montgomery St,40.719420,-74.050990,29655,Subscriber,1958,1
42252,268,2019-10-31 23:53:45.6170,2019-10-31 23:58:13.8980,3203,Hamilton Park,40.727596,-74.044247,3186,Grove St PATH,40.719586,-74.043117,26314,Subscriber,1964,1

In [19]:
Sept_Nov2019_df = Sept2019_df
Sept_Nov2019_df = Sept_Nov2019_df.append(Oct2019_df, ignore_index=True)
Sept_Nov2019_df = Sept_Nov2019_df.append(Nov2019_df, ignore_index=True)

Sept_Nov2019_df.to_csv("CSV/cleaned/2019.csv")
Sept_Nov2019_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,145,2019-09-01 00:00:37.6920,2019-09-01 00:03:03.0100,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,29303,Subscriber,1991,1
1,212,2019-09-01 00:03:00.6000,2019-09-01 00:06:33.3420,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,29297,Subscriber,1993,2
2,569,2019-09-01 00:07:13.0020,2019-09-01 00:16:42.8610,3214,Essex Light Rail,40.712774,-74.036486,3184,Paulus Hook,40.714145,-74.033552,29435,Customer,1977,1
3,1380,2019-09-01 00:07:25.3350,2019-09-01 00:30:26.1640,3214,Essex Light Rail,40.712774,-74.036486,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,29509,Subscriber,1965,1
4,1346,2019-09-01 00:07:56.4670,2019-09-01 00:30:22.5440,3214,Essex Light Rail,40.712774,-74.036486,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,29226,Subscriber,1968,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122289,77,2019-11-30 23:30:07.7850,2019-11-30 23:31:25.7730,3638,Washington St,40.724294,-74.035483,3202,Newport PATH,40.727224,-74.033759,29492,Subscriber,1979,1
122290,145,2019-11-30 23:40:45.3790,2019-11-30 23:43:10.5660,3211,Newark Ave,40.721525,-74.046305,3278,Monmouth and 6th,40.725685,-74.048790,40971,Subscriber,1978,1
122291,99,2019-11-30 23:41:55.3310,2019-11-30 23:43:34.3320,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,26198,Subscriber,1991,1
122292,594,2019-11-30 23:52:50.2410,2019-12-01 00:02:44.2960,3213,Van Vorst Park,40.718489,-74.047727,3639,Harborside,40.719252,-74.034234,29527,Subscriber,1981,1
122293,329,2019-11-30 23:56:27.6680,2019-12-01 00:01:57.0120,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,26163,Subscriber,1977,1

In [23]:
all_df = Sept_Nov2018_df.append(Sept_Nov2019_df, ignore_index=True)
all_df.to_csv("CSV/cleaned/all.csv")
all_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,284,2018-09-01 01:48:22.0320,2018-09-01 01:53:06.9130,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26303,Subscriber,1984,1
1,370,2018-09-01 01:48:22.5010,2018-09-01 01:54:32.9270,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29667,Subscriber,1984,1
2,1181,2018-09-01 09:37:04.3070,2018-09-01 09:56:45.3280,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26307,Customer,1994,1
3,383,2018-09-01 09:44:46.0030,2018-09-01 09:51:09.9230,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,29261,Subscriber,1987,1
4,377,2018-09-01 09:44:46.1850,2018-09-01 09:51:03.6330,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,33665,Subscriber,1985,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225359,77,2019-11-30 23:30:07.7850,2019-11-30 23:31:25.7730,3638,Washington St,40.724294,-74.035483,3202,Newport PATH,40.727224,-74.033759,29492,Subscriber,1979,1
225360,145,2019-11-30 23:40:45.3790,2019-11-30 23:43:10.5660,3211,Newark Ave,40.721525,-74.046305,3278,Monmouth and 6th,40.725685,-74.048790,40971,Subscriber,1978,1
225361,99,2019-11-30 23:41:55.3310,2019-11-30 23:43:34.3320,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,26198,Subscriber,1991,1
225362,594,2019-11-30 23:52:50.2410,2019-12-01 00:02:44.2960,3213,Van Vorst Park,40.718489,-74.047727,3639,Harborside,40.719252,-74.034234,29527,Subscriber,1981,1
225363,329,2019-11-30 23:56:27.6680,2019-12-01 00:01:57.0120,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,26163,Subscriber,1977,1